### ISSUE TITLE
Multiple namespaces

### ISSUE THREAD

**Issue by nWidart** [jildertmiedema/laravel-tactician#1]
Hello,

Is it possible to have multiple command/command handlers namespaces configurable ?
I have my apps separated into modules, there's a command/handler namespace for every one of them.

Thanks!

**Comment by jildertmiedema** [comment]
Hi,

You can overwrite the locator:

```
$this->bind('tactician.handler.locator', function () {
    return new YourLocator();
});
```

If it implements `League\Tactician\Handler\Locator\HandlerLocator` it should work.

You can do some regular expression on the `$commandName`. 

Another solution is one command bus per module.
